version: "3"

services:
  # client:
  #   build: ./client
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./client:/data
  #   environment:
  #     - API_URL=http://localhost:8081/
  #
  server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/data
    depends_on:
      - mongo-server
    environment:
      - DATABASE_URL=mongo-server:27017

  mongo-server:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
