version: "3"

services:
  client:
    build: ./client
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./client:/data
    depends_on:
      - server
    environment:
      - API_URL=http://localhost:8081/
      - NODE_ENV=development

  server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/data
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb:27017
      - NODE_ENV=development

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
