version: "3"

services:
  test_runner:
    build:
      context: ./api
      dockerfile: Dockerfile.test
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/data
    depends_on:
      - mongo-server
    environment:
      - DATABASE_URL=mongo-server:27017
      - NODE_ENV=test

  mongo-server:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    logging:
      driver: "none"
